Repository Connor-Bernard/gradeView, pull requests merged in 2023-03, with the labels that each got.

#45 modified and made constant names less ambiguous
  api/server.js
Labels: documentation

#46 Made accordion tabs correspond to the tabs on spreadsheet
  website/src/components/GradeAccordion.js
  website/src/views/home.js
Labels: enhancement

#47 Env reconfig
  .env
  .gitignore
  README.md
  api/auth/.gitkeep
  api/config/default.json
  api/package-lock.json
  api/package.json
  api/server.js
  docker-compose.yml
  package-lock.json
  website/.env
  website/production/.env
  website/production/middleware.js
  website/src/setupProxy.js
Labels: documentation, enhancement
